using Content.Client.UserInterface.Systems.Emotes.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.UserInterface.Systems.Emotes.Windows;

[GenerateTypedNameReferences]
public sealed partial class EmotesWindow : DefaultWindow
{
    private bool _isLocked = false;
    private float _lockTimer = 0.5f;

    public EmotesWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetButtons(IEnumerable<EmoteButton> buttons)
    {
        EmotesGrid.RemoveAllChildren();
        foreach (var button in buttons)
        {
            EmotesGrid.AddChild(button);
        }
    }

    public void StartLocking()
    {
        _lockTimer += 1.0f;
        UpdateLocking();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
        {
            _lockTimer -= args.DeltaSeconds;
        }

        if (_isLocked != _lockTimer > 0f)
        {
            UpdateLocking();
        }
    }

    private void UpdateLocking()
    {
        _isLocked = _lockTimer > 0f;
        foreach (var child in EmotesGrid.Children)
        {
            if (child is EmoteButton button)
            {
                button.Disabled = _isLocked;
            }
        }
    }
}
