"T: No C#":
- changed-files:
  - all-globs-to-all-files: "!**/*.cs"

"A: Sprites":
- changed-files:
  - any-glob-to-any-file: '**/*.rsi/**'

"A: Mapping":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Maps/**'

    - 'Resources/Prototypes/Maps/**'
    - 'Resources/Prototypes/_Carpmosia/Maps/**'

    - 'Resources/Prototypes/Decals/**'
    - 'Resources/Prototypes/_Carpmosia/Decals/**'

    - 'Resources/Textures/Decals/**'
    - 'Resources/Textures/_Carpmosia/Decals/**'

"A: UI/UX":
- changed-files:
  - any-glob-to-any-file: '**/*.xaml*'

"A: Shaders":
- changed-files:
  - any-glob-to-any-file:
    - '**/*.swsl'

    - 'Resources/Prototypes/Shaders/**'
    - 'Resources/Prototypes/_Carpmosia/Shaders/**'

"A: Audio":
- changed-files:
  - any-glob-to-any-file: '**/*.ogg'

"A: Guidebook":
- all:
  - changed-files:
    - any-glob-to-any-file:
      - 'Resources/ServerInfo/**'

      - 'Resources/Prototypes/Guidebook/**'
      - 'Resources/Prototypes/_Carpmosia/Guidebook/**'

    - all-globs-to-all-files:
      - '!Resources/Prototypes/Guidebook/rules.yml'
      - '!Resources/Prototypes/_Carpmosia/Guidebook/rules.yml'

      - '!Resources/Prototypes/Guidebook/security.yml'
      - '!Resources/Prototypes/_Carpmosia/Guidebook/security.yml'

      - '!Resources/ServerInfo/Guidebook/ServerRules/**'
      - '!Resources/ServerInfo/_Carpmosia/Guidebook/ServerRules/**'

"A: Rules":
- all:
  - changed-files:
    - any-glob-to-any-file:
      - 'Resources/Prototypes/Guidebook/rules.yml'
      - 'Resources/Prototypes/_Carpmosia/Guidebook/rules.yml'

      - 'Resources/ServerInfo/Guidebook/ServerRules/**'
      - 'Resources/ServerInfo/_Carpmosia/Guidebook/ServerRules/**'

    - all-globs-to-all-files:
      - '!Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/**'
      - '!Resources/ServerInfo/_Carpmosia/Guidebook/ServerRules/SpaceLaw/**'

"A: Space Law":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Prototypes/Guidebook/security.yml'
    - 'Resources/Prototypes/_Carpmosia/Guidebook/security.yml'

    - 'Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/**'
    - 'Resources/ServerInfo/_Carpmosia/Guidebook/ServerRules/SpaceLaw/**'

"A: Loadouts":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Prototypes/Loadouts/**'
    - 'Resources/Prototypes/_Carpmosia/Loadouts/**'

"A: Recipes":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Prototypes/Recipes/**'
    - 'Resources/Prototypes/_Carpmosia/Recipes/**'

"A: Objectives":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Prototypes/Objectives/**'
    - 'Resources/Prototypes/_Carpmosia/Objectives/**'

"A: Lawsets":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Locale/en-US/station-laws/laws.ftl'
    - 'Resources/Locale/en-US/_Carpmosia/station-laws/laws.ftl'

    - 'Resources/Prototypes/silicon-laws.yml'
    - 'Resources/Prototypes/_Carpmosia/silicon-laws.yml'

"A: Lobby Art":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Prototypes/lobbyscreens.yml'
    - 'Resources/Prototypes/_Carpmosia/lobbyscreens.yml'

    - 'Resources/Textures/LobbyScreens/**'
    - 'Resources/Textures/_Carpmosia/LobbyScreens/**'
