# Robust.Cvars
net.pvs = false
build.fork_id = "carpmapping"
game.hostname = "𓆟 | Carpmapping"
game.desc = "Carpmosia Mapping Server"

# CCVars.Admin.Rules
rules.time = 1

# CCVars.Game
game.lobbyenabled = false
game.defaultpreset = "sandbox"
game.map = "Dev"
game.role_timers = false
game.role_loadout_timers = false
game.role_whitelist = false

# CCVars.Server
server.uptime_restart_minutes = 0
server.lobby_name = "Carpmapping"

# CCVars.Shuttle
shuttle.grid_fill = false
shuttle.auto_call_time = 0
shuttle.emergency = false
shuttle.arrivals = false
shuttle.preload_grids = false
