# Robust.Cvars
build.fork_id = "carpmosia"
game.hostname = "[EN][LRP++] 𓆟 | Carpmosia"
game.desc = "A chill LRP++ server\nWe just launched, come join and have fun!"
hub.tags = "lang:en,rp:low,rp:med,region:eu_w,region:luna,no_tag_infer"
replay.max_compressed_size = 2097152
replay.max_uncompressed_size = 4194304

# CCVars.Admin.Rules
rules.time = 180

# CCVars.Discord
discord.news_webhook_send_during_round = true

# CCVars.Game
game.lobbyduration = 300
game.round_restart_time = 300

# CCVars.Replays
replay.auto_record_name = "{year}_{month}/{year}_{month}_{day}/{year}_{month}_{day}-{hour}_{minute}-round_{round}.zip"

# CCVars.Server
server.uptime_restart_minutes = 1440
server.lobby_name = "Carpmosia"

