# Robust.Cvars
build.fork_id = "carptestimg"
game.hostname = "𓆟 | Carptesting"
game.desc = "Carpmosia Test Server"

# CCVars.Admin.Rules
rules.time = 1

# CCVars.Game
game.defaultpreset = "greenshift"
game.map = "Elkridge"

# CCVars.Server
server.uptime_restart_minutes = 720
server.lobby_name = "Carptesting"

# CCVars.Shuttle
shuttle.auto_call_time = 0
