using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class IconButton : Button
{
    public IconButton()
    {
        RobustXamlLoader.Load(this);
    }
}
